<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div class="block <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?> card filter-option py-4 px-8 mb-6">
    <div class="content <?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>-content md:block"
         id="<?= $escaper->escapeHtmlAttr($block->getBlockCss()) ?>"
    >
        <?= $block->getChildHtml() ?>
    </div>
</div>
<!--<script>-->
<!--    function initAccountNavigation() {-->
<!--        return {-->
<!--            isMobile: false,-->
<!--            blockOpen: false,-->
<!--            checkIsMobileResolution() {-->
<!--                const mobileElement = this.$refs.AccountNavigationMobileToggleIcon;-->
<!--                this.isMobile = mobileElement-->
<!--                    ? getComputedStyle(mobileElement).display !== 'none'-->
<!--                    : window.matchMedia('(max-width: 767px)').matches; // Fallback to `md` breakpoint-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--</script>-->
