<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HeroiconsOutline;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */

// The item to render is set on the block before the template is rendered:
$column = $block->getData('item');

$heroicons = $viewModels->require(HeroiconsOutline::class);


$buttonLabel = $column->getButton();
$buttonUrl = $column->getButtonUrl();
?>

<div class="flex gap-6">
    <div class="flex-1 w-full"><p class="mt-2 block text-base font-medium text-white truncate pointer-events-none">
            <?= $escaper->escapeHtml($column->getTitle()) ?>
        </p>
        <p class="mt-2 block text-xs text-white pointer-events-none">
            <?= /** @noEscape */
            $column->getDescription(); ?>
        </p>
        <div class="flex flex-nowrap gap-2 mt-2">
            <button
                aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                tabindex="-1"
                class="text-white bg-buttonBg-darker w-20  p-1 focus:outline-none flex justify-center hover:bg-buttonBg-lighter ease-in-out transition"
                :class="{'opacity-25 pointer-events-none' : active === 0 }"
                @click="scrollPrevious">
                <?= $heroicons->arrowLeftHtml("w-2 h-2", 25, 25) ?>
            </button>
            <button
                aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                tabindex="-1"
                class="text-white bg-buttonBg-darker w-20  p-1 focus:outline-none flex justify-center hover:bg-buttonBg-lighter ease-in-out transition"
                :class="{'opacity-25 pointer-events-none' : active >= itemCount-pageSize }"
                @click="scrollNext">
                <?= $heroicons->arrowRightHtml("w-2 h-2", 25, 25) ?>
            </button>
        </div>

    </div>
    <div class="flex-1 w-full">
        <a href="<?= $escaper->escapeUrl($column->getButtonUrl()) ?>"
           class="block w-full rounded-lg overflow-hidden"
        >
            <img src="<?= $escaper->escapeUrl($column->getThumbnail()); ?>"
                 alt="<?= $escaper->escapeHtmlAttr($column->getTitle()) ?>"
                 loading="lazy"
                 class="object-cover hover:opacity-75 w-auto min-h-14"
            >
        </a>
    </div>
    <?php if ($buttonLabel && $buttonUrl): ?>
        <div class="mt-4 sm:flex">
            <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($buttonUrl)) ?>"
               class="inline-flex btn btn-primary">
                <?= $escaper->escapeHtml($buttonLabel) ?>
            </a>
        </div>
    <?php endif; ?>
</div>
